kind: pipeline
type: docker
name: build

trigger:
 event:
 - cron
 - push
 - pull_request
 - tag


steps:
- name: Build with Gradle
  image: gradle:7.2.0-jdk16
  commands:
  - 'chmod +x gradlew'
  - './gradlew build'

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - BukkitReflectionUtil - build
  when:
    status: [ failure ]